server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pedidos
      username: admin
      password: admin
      authentication-database: admin
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER